3_1: 3_1.c
	gcc 3_1.c -o 3_1 
clean3_1:
	rm 3_1

3_2: 3_2.c
	gcc 3_2.c -o 3_2
clean3_2:
	rm 3_2

3_3: 3_3.c
	gcc 3_3.c -o 3_3
cleanall:
	rm 3_3

cleanall:
	rm 3_1
	rm 3_2
	rm 3_3                       
