2_1: 2_1.c
	gcc 2_1.c -o 2_1
clean2_1:
	rm 2_1

2_2: 2_2.c
	gcc 2_2.c -o 2_2
clean2_1:
	rm 2_2

2_3: 2_3.c
	gcc 2_3.c -o 2_3
clean2_3:
	rm 2_3

2_4: 2_4.c
	gcc 2_4.c -o 2_4
clean2_4:
	rm 2_4

2_5: 2_5.c
	gcc 2_5.c -o 2_5
clean2_5:
	rm 2_5

2_6: 2_6.c
	gcc 2_6.c -o 2_6
clean2_6:
	rm 2_6
	
2_7: 2_7.c
	gcc 2_7.c -o 2_7
clean2_7:
	rm 2_7

2_8: 2_8.c
	gcc 2_8.c -o 2_8
clean2_8:
	rm 2_8

2_9: 2_9.c
	gcc 2_9.c -o 2_9
clean2_9:
	rm 2_9

2_10: 2_10.c
	gcc 2_10.c -o 2_10
clean2_10:
	rm 2_10
		
cleanall: 
	rm 2_1
	rm 2_2
	rm 2_3
	rm 2_4
	rm 2_5
	rm 2_6
	rm 2_7
	rm 2_8
	rm 2_9
	rm 2_10           
